modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="createelevatorcc"
version="1.0.2"
displayName="CC:LiftLink"
authors="Tom"
description='''
CC:LiftLink - CC:Tweaked elevator contact peripheral for Create elevators.
Works from a single linked redstone contact, with pulley tracking only used when available.
'''

[[dependencies.createelevatorcc]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.createelevatorcc]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.createelevatorcc]]
modId="create"
mandatory=true
versionRange="[6.0.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.createelevatorcc]]
modId="computercraft"
mandatory=true
versionRange="[1.116.1,)"
ordering="AFTER"
side="BOTH"
